on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest 


    steps:
      - name: 'Try to push on github'
        run: pwd 

      - name: 'print my name'
        run: echo yara

      - name: 'Show folder content1'
        run: ls -a

      - uses: actions/checkout@v3

      - name: 'Show folder content2'
        run: ls -a
